name: SBT Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Test Scala project
      run: |
        echo Running Tests
        sbt test
